export var student_id = "string";
export var full_name = "string";
export var gender = "string";
export var enrollment_type = "string";
export var year_of_enrollment = 0;
export var sc_status = false;
export var pr_status = false;
export var nationality = "string";
export var phone_number =0;
export var email_sutd= "string";
export var email_personal = "string";
export var local_addr_post_code = "string";
export var local_addr_street = "string";
export var local_addr_unit = "string";
export var attended_events = []; //list of strings
export var disciplinary_records = []; // list of record objects
export var preference_roommate = []; //list of string
export var preference_room = null; // RoomProfile object
export var preference_lifestyle = null; // Lifestyle profile object
export var is_house_guardian = false;
export var travel_time = 0;
