export var uid = "string";
export var room_type  = "string";
export var block = "string";
export var level = 0;
export var location_idx = 0;
export var dist_to_lift = 0;
export var dist_to_washroom =0;
export var near_to_lift = false;
export var near_to_washroom = false;
export var window_facing = "string";
export var face_campus = false;
export var face_airport = false;
export var face_building = false;
export var current_effective_contract_count = 0;
export var all_contracts = []// list of contract uids